all:
	javac StdAudio.java StdDraw.java StdOut.java StdIn.java
	javac *.java

clean:
	rm *.class
	
std:
	wget http://introcs.cs.princeton.edu/java/15inout/StdAudio.java
	wget http://introcs.cs.princeton.edu/java/15inout/StdDraw.java
	wget http://introcs.cs.princeton.edu/java/15inout/StdOut.java
	wget http://introcs.cs.princeton.edu/java/15inout/StdIn.java

	javac StdAudio.java StdDraw.java StdOut.java StdIn.java