Subjects = {
    "Mathematics": "Mathematics",
    "Physics": "Physics",
	"Art": "Art",
	"Geography": "Geography",
	"History": "History",
    "English": "English",
    "German": "German",
    "French": "French",
    "Spanish": "Spanish",
	"Music": "Music",
	"Business studies": "Business studies",
	"Drama": "Drama",
	"Information and communication technology": "Information and communication technology",
	"Religion": "Religion",
	"Ancient Greek": "Ancient Greek",
	"Biology": "Biology",
	"Chemistry": "Chemistry",
	"Ethic(s)": "Ethic(s)",
	"Latin": "Latin",
	"Psychology": "Psychology"
}
